services:
  - type: web
    name: dspipexp-api
    env: docker
    region: singapore
    plan: starter
    healthCheckPath: /api/v1/health
    buildCommand: docker build -t dspipexp-api .
    startCommand: docker run -p $PORT:8000 -e DATABASE_URL=$DATABASE_URL -e REDIS_URL=$REDIS_URL -e PORT=8000 dspipexp-api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dspipexp-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: dspipexp-redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: AUDIO_STORAGE_PATH
        value: /tmp/audio
      - key: CACHE_STORAGE_PATH
        value: /tmp/cache
    autoDeploy: true

  - type: redis
    name: dspipexp-redis
    region: singapore
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: []

databases:
  - name: dspipexp-db
    region: singapore
    plan: starter 