services:
  - type: web
    name: dspipexp-api
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /api/v1/health
    buildCommand: docker build -t dspipexp-api .
    startCommand: docker run -p $PORT:10000 -e DATABASE_URL=$DATABASE_URL -e REDIS_URL=$REDIS_URL -e PORT=10000 dspipexp-api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dspipexp-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: dspipexp-redis
          type: redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: AUDIO_STORAGE_PATH
        value: /tmp/audio
      - key: CACHE_STORAGE_PATH
        value: /tmp/cache
    autoDeploy: true

  - type: redis
    name: dspipexp-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

databases:
  - name: dspipexp-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere 