db_url = "postgresql://neondb_owner:npg_EJGXPcthF4M3@ep-rapid-tooth-a12tv1np-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
genius_api_key = "7HDXF_XZrYc9a6MJe9SA7A2J3XQXdQv5OytJCgHeTvjTBFp8XIR4Tlj40P7G2kOe"
youtube_api_key = "your-youtube-api-key"
lastfm_api_key = "4a8bc9abcb3407a4cc9b2cf1a0e0e692"